name: §4§lTestGUI

list:
  0:
    0:
      material:
      name:
      lore:
        -
      commands:
        -
      bypassCommands:
        -
    1:
      material:
      name:
      lore:
        -
  1:
    0:
      material:
      name:
      lore:
        -